name: "Tool Integration"

on:
  push:
    paths:
      - 'tools_settings/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REQUIREMENTS_PATH: 'requirements.txt'
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Setup installation requirements"
        run: |
          pip install --upgrade pip
          pip install wheel pylint
          pip install -r ${{ env.REQUIREMENTS_PATH }}
          python3 -m spacy download en_core_web_lg

      - name: "Run TestToolIntegration"
        run: |
          python3 ./test/tool_integration/test_tool_integration.py
